### ISSUE TITLE
Investigate a port to Django 3

### ISSUE THREAD

**Issue by wave100** [RPIForge/website#27]
Django 3 is out as of 12/2/19 - figure out how much refactoring will be necessary to get this site running with it.

**Comment by wave100** [comment]
I've run this locally and haven't noticed any issues after tweaking some configuration (ff22772). Requires further testing before implementation.

**Comment by HonakerM** [comment]
Should be able to close this once the refactor is pulled in

**Comment by HonakerM** [comment]
We are now on Django 3.2
