### ISSUE TITLE
Automatic Log-Out

### ISSUE THREAD

**Issue by wave100** [RPIForge/website#6]
Log the active user out after ten minutes for security purposes - should be done by adding a script tag pointing to the following code to the generic page template:
```
var logout_event;

function notify() {
alert("Logged out automatically due to inactivity.");
}

 
function automatic_logout() {
location.replace("https://www.rpiforge.dev/controllers/logout_controller.php");
setTimeout(notify, 10);
}

 
logout_event = setTimeout(automatic_logout, 1000 * 60 * 10);

 
document.onclick = function() {
clearTimeout(logout_event);
logout_event = setTimeout(automatic_logout, 1000 * 60 * 10);
}
```

**Comment by wave100** [comment]
This has been backported to the current website

**Comment by HonakerM** [comment]
@wave100 do we want to logout due to inactivity or just log out no matter what? We could set the cookie session age with something like this `SESSION_COOKIE_AGE = 1800` in setting.py but this would force logout no matter what

**Comment by wave100** [comment]
Inactivity - this is mainly for when people leave their accounts logged in
on our public machines.

**Comment by wave100** [comment]
Added in f3c6a1c
